version: 0.2

env:
  parameter-store:
    GITHUB_TOKEN: "/continuous_apply/github_token"

phases:
  install:
    commands:
      - ls -al ${CODEBUILD_SRC_DIR}/chapter27/continuous/scripts/install.sh
      - sh ${CODEBUILD_SRC_DIR}/chapter27/continuous/scripts/install.sh
  build:
    commands:
      - sh ${CODEBUILD_SRC_DIR}/chapter27/continuous/scripts/build.sh
